import { AppData } from './types';

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function daysAhead(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

export const initialData: AppData = {
  personas: [
    {
      id: 'admin',
      name: 'Pastor Paul Liu',
      role: 'admin',
      personId: 'qing-liu',
      assignedPeopleIds: ['long-cheng', 'zachary-daily', 'lizhi-daily', 'yinong-fang', 'jacob-eades', 'jake-guerrero', 'tyler-levin', 'rachel-liu', 'yingguang-liu', 'tom-mullett', 'mark-miller', 'steven-ni', 'chris-nixon', 'vicki-miller', 'jay-song', 'john-thompson', 'zhenying-wang', 'aihua-yi', 'weilong-zhuo', 'peter-zhuang', 'lujia-yin', 'zach-sun', 'blake-levin', 'eric-chen', 'daniel-braswell', 'bill-cosgrove'],
    },
    {
      id: 'shepherd-1',
      name: 'Long Cheng',
      role: 'shepherd',
      personId: 'long-cheng',
      assignedPeopleIds: ['xiang-you', 'daini-eades', 'fangyu-ai', 'jacob-eades', 'miranda-sparklin', 'ryan-sparklin', 'yu-ren-liu', 'anne-park-braswell', 'david-green', 'mattaniah-wilson', 'zach-sun', 'eric-chen', 'joseph-kuwashima', 'zixuan-chen', 'michelle-wang', 'cole-richards', 'daniel-braswell', 'angelina-chen', 'ce-liu', 'peter-macranie'],
    },
    {
      id: 'shepherd-2',
      name: 'Asia Brady',
      role: 'shepherd',
      personId: 'asia-brady',
      assignedPeopleIds: ['moana-xia', 'gillian-tang', 'lin-ho', 'mei-li', 'marni-thompson', 'miranda-sparklin', 'jessica-wang', 'ella-zajonc', 'leanne-hanson', 'natalie-cummings', 'xena-cosgrove'],
    },
    {
      id: 'welcome-team',
      name: 'Welcome Team',
      role: 'welcome-team',
      personId: 'miranda-sparklin',
      assignedPeopleIds: [],
    },
  ],

  people: [
    {
      id: 'xiang-you',
      englishName: 'Bob You',
      chineseName: 'Xiang',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['david-kao', 'shepherd-1'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'long-cheng',
      englishName: 'Long Cheng',
      gender: 'male',
      isShepherd: true,
      appRole: 'shepherd' as const,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      familyId: 'cheng-household',
      groupIds: ['students', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'david-kao',
      englishName: 'David Kao',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['luke-zhang', 'shannon-tsai'],
      familyId: 'kao-household',
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yu-shan-tsai',
      englishName: 'Yu-Shan Tsai',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['david-kao', 'melinda-li'],
      familyId: 'kao-household',
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'harmon-blanding',
      englishName: 'Harmon Blanding',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bonnie-drumheller',
      englishName: 'Bonnie Drumheller',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'eva-brooks',
      englishName: 'Eva Brooks',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'janette-blanding',
      englishName: 'Janette Blanding',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kwan-cheng',
      englishName: 'Sonia Cheng',
      chineseName: 'Kwan',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zachary-daily',
      englishName: 'Zachary Daily',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lyle-brooks',
      englishName: 'Pete Brooks',
      chineseName: 'Lyle',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jimmy-cash',
      englishName: 'Jimmy Cash (passed away)',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'phyllis-cash',
      englishName: 'Phyllis Cash',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lizhi-daily',
      englishName: 'Lizhi Daily',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'hanping-bao',
      englishName: 'Hanping Bao',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yinong-fang',
      englishName: 'Yinong Fang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'daini-eades',
      englishName: 'Daini Eades',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-1'],
      familyId: 'eades-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'asia-brady',
      englishName: 'Asia Brady',
      gender: 'female',
      isShepherd: true,
      appRole: 'shepherd' as const,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'keimei-chang',
      englishName: 'KeiMei Chang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'fangyu-ai',
      englishName: 'Fangyu Ai',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: [],
      familyId: 'cheng-household',
      groupIds: ['students', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'james-forbes',
      englishName: 'James Forbes',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['men'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'diane-francis',
      englishName: 'Diane Francis',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jacob-eades',
      englishName: 'Jacob Eades',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'admin'],
      familyId: 'eades-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'faye-gallier',
      englishName: 'Faye Gallier',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gordon-goh',
      englishName: 'Gordon Goh',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anna-goh',
      englishName: 'Anna Goh',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'long-jing',
      englishName: 'James Jing',
      chineseName: 'Long',
      gender: 'male',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'huina-hu',
      englishName: 'Huina Hu',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gillian-tang',
      englishName: 'Gillian Tang',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-2'],
      familyId: 'tang-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lui-kuong-lai',
      englishName: 'Lui Kuong Lai',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lin-ho',
      englishName: 'Lisa Levin',
      chineseName: 'Lin Ho',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['gillian-tang', 'shepherd-2'],
      familyId: 'levin-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yixin-jin',
      englishName: 'Joy Jin',
      chineseName: 'Yixin',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['kevin-tang', 'lin-ho', 'gillian-tang', 'tyler-levin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jack-kerns',
      englishName: 'Jack Kerns',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'mei-li',
      englishName: 'Melinda Li',
      chineseName: 'Mei',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shannon-tsai', 'shepherd-2'],
      familyId: 'zhang-household',
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jake-guerrero',
      englishName: 'Jake Guerrero',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'faith-lang',
      englishName: 'Faith Lang',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['lin-ho', 'gillian-tang', 'melinda-li'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'xiaosang-huang',
      englishName: 'Xiaosang Huang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'tyler-levin',
      englishName: 'Tyler Levin',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin', 'john-thompson', 'kevin-tang'],
      familyId: 'levin-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'brenda-kerns',
      englishName: 'Brenda Kerns',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'rachel-liu',
      englishName: 'Rachel Li',
      chineseName: '李金鹤',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: [],
      familyId: 'liu-family',
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yingguang-liu',
      englishName: 'Yingguang Liu',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'tom-mullett',
      englishName: 'Tom Mullett',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson', 'admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jennifer-mariner',
      englishName: 'Jennifer Mariner',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'qing-liu',
      englishName: 'Paul Liu',
      chineseName: 'Qing',
      gender: 'male',
      isShepherd: true,
      appRole: 'admin' as const,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song', 'john-thompson'],
      familyId: 'liu-family',
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'mark-miller',
      englishName: 'Mark Miller',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'steven-ni',
      englishName: 'Steven Ni',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['kevin-tang', 'tyler-levin', 'admin'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'chris-nixon',
      englishName: 'Chris Nixon',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson', 'admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'karen-nixon',
      englishName: 'Karen Nixon',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'brandon-roos',
      englishName: 'Brandon Roos',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'marni-thompson',
      englishName: 'Marni Thompson',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson', 'shepherd-2'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'vicki-miller',
      englishName: 'Vicki Miller',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'franklin-wang',
      englishName: 'Franklin Wang',
      gender: 'male',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['david-kao'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'iona-nixon',
      englishName: 'Iona Nixon',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'miranda-sparklin',
      englishName: 'Miranda Sparklin',
      appRole: 'welcome-team' as const,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'shepherd-2'],
      familyId: 'sparklin-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jessica-wang',
      englishName: 'Jessica Wang',
      chineseName: 'Huijin',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['melinda-li', 'shepherd-2', 'shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ryan-sparklin',
      englishName: 'Ryan Sparklin',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['kevin-tang', 'tyler-levin', 'shepherd-1'],
      familyId: 'sparklin-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shawn-thompson',
      englishName: 'Shawn Thompson',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jay-song',
      englishName: 'Jay Song',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin', 'john-thompson'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'john-thompson',
      englishName: 'John Thompson',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song', 'admin'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sandra-west',
      englishName: 'Sandra West',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'amber-wang',
      englishName: 'Amber Wang',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zhenying-wang',
      englishName: 'Zhenying Wang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin', 'rachel-liu'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'juiying-yu',
      englishName: 'Juiying Yu',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ella-zajonc',
      englishName: 'Ella Zajonc',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['shannon-tsai', 'shepherd-2', 'melinda-li'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yingwen-wang',
      englishName: 'Wendy Wang',
      chineseName: 'Yingwen',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yu-zhou',
      englishName: 'Yu Zhou',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'xinyi-zhang',
      englishName: 'Xinyi Zhang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['melinda-li', 'shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'may-zhan',
      englishName: 'May Zhan',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kuo-zhang',
      englishName: 'Jonathan Zhang',
      chineseName: 'Kuo',
      membershipStatus: 'member',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: ['kevin-tang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'aihua-yi',
      englishName: 'Aihua Yi',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lianjie-xue',
      englishName: 'Lianjie Xue',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jiade-zhang',
      englishName: 'Jiade Zhang',
      gender: 'male',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['david-kao'],
      familyId: 'zhang-household',
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'weilong-zhuo',
      englishName: 'Weilong Zhuo',
      gender: 'male',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'peter-zhuang',
      englishName: 'Peter Zhuang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['david-kao', 'admin'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'adoniah',
      englishName: 'Adoniah',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bekah',
      englishName: 'Bekah',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'evie-jang',
      englishName: 'Evie Jang',
      membershipStatus: 'sunday-attendee',
      isBeingDiscipled: true,
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'christine',
      englishName: 'Christine',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'hyeonyin',
      englishName: 'Hyeonyin',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'david',
      englishName: 'David',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'grant',
      englishName: 'Grant',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jack-donohue',
      englishName: 'Jack Donohue',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(4),
    },
    {
      id: 'emily',
      englishName: 'Emily',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'esther',
      englishName: 'Esther',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'elisa-garcia',
      englishName: 'Elisa Garcia',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(8),
    },
    {
      id: 'cameron',
      englishName: 'Cameron',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'izzy-dreisilker',
      englishName: 'Izzy Dreisilker',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'conghoon-choi',
      englishName: 'Conghoon Choi',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(2),
    },
    {
      id: 'andrew-g',
      englishName: 'Andrew G',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'emily-hadden',
      englishName: 'Emily Hadden',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ariana',
      englishName: 'Ariana',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'harrel',
      englishName: 'Harrel',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jadon',
      englishName: 'Jadon',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yu-ren-liu',
      englishName: 'Josh Liu',
      chineseName: 'Yu Ren',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jonathan',
      englishName: 'Jonathan',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'melissa',
      englishName: 'Melissa',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joslyn',
      englishName: 'Joslyn',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lujia-yin',
      englishName: 'Lujia Yin',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'leah-morgan',
      englishName: 'Leah Morgan',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kellyn-hale',
      englishName: 'Kellyn Hale',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kristiana-underwood',
      englishName: 'Kristiana Underwood',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'natalia',
      englishName: 'Natalia',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'nicholas',
      englishName: 'Nicholas',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'luca-walton',
      englishName: 'Luca Walton',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'keeley-sheppard',
      englishName: 'Keeley Sheppard',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'marcos',
      englishName: 'Marcos',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zach-mcclanrance',
      englishName: 'Zach Mcclanrance',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sara-ellington',
      englishName: 'Sara Ellington',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'soohyeon-cho',
      englishName: 'Soohyeon Cho',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'umairli',
      englishName: 'Umairli',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'timeea',
      englishName: 'Timeea',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sergio',
      englishName: 'Sergio',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sara-xavier',
      englishName: 'Sara Xavier',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'seobeen',
      englishName: 'Seobeen',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'daiwei-huang',
      englishName: 'Daiwei Huang',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['charley-xia'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anne-park-braswell',
      englishName: 'Anne Park-Braswell',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-1'],
      familyId: 'braswell-family',
      groupIds: ['young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'grace-phillips',
      englishName: 'Grace Phillips',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'elisabeth-grace-goode',
      englishName: 'Elisabeth Grace Goode',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'heidi-allen',
      englishName: 'Heidi Allen',
      gender: 'female',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['melinda-li'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jubilee-harris',
      englishName: 'Jubilee Harris',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'david-green',
      englishName: 'David Green',
      gender: 'male',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'mattaniah-wilson',
      englishName: 'Mattaniah Wilson',
      membershipStatus: 'membership-class',
      language: 'english',
      assignedShepherdIds: ['shepherd-1'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'chase-cartwright',
      englishName: 'Chase Cartwright',
      membershipStatus: 'membership-class',
      language: 'english',
      assignedShepherdIds: ['moana-xia', 'charley-xia'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kaiya-west',
      englishName: 'Kaiya West',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'person-row-128',
      englishName: '家昊 崔',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['david-kao'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'deborah-liu',
      englishName: 'Deborah Liu',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shannon-tsai', 'melinda-li'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jessica-fang',
      englishName: 'Jessica Fang',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['shannon-tsai', 'melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alaina-sefiane',
      englishName: 'Alaina Sefiane',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zach-sun',
      englishName: 'Zach Sun',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['admin', 'shepherd-1'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jackson-zakariasen',
      englishName: 'Jackson Zakariasen',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kevin-tang',
      englishName: 'Kevin Tang',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['tyler-levin'],
      familyId: 'tang-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lu-chang',
      englishName: 'Lu Chang',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'debbie-liu',
      englishName: 'Debbie Liu',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['lin-ho', 'gillian-tang'],
      familyId: 'liu-family',
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gary-yao',
      englishName: 'Gary Yao',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['david-kao', 'luke-zhang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'blake-levin',
      englishName: 'Blake Levin',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['john-thompson', 'admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'eric-chen',
      englishName: 'Eric Chen',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['admin', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bekkah-shi',
      englishName: 'Bekkah Shi',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'leanne-hanson',
      englishName: 'Leanne Hanson',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-2', 'john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shane-wang',
      englishName: 'Shane Wang',
      membershipStatus: 'archive',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'boaz-mao',
      englishName: 'Boaz Mao',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'cavanaugh-oleary',
      englishName: 'Cavanaugh Oleary',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'natalie-cummings',
      englishName: 'Natalie Cummings',
      membershipStatus: 'membership-class',
      language: 'english',
      assignedShepherdIds: ['moana-xia', 'shepherd-2'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gabriel-daily',
      englishName: 'Gabriel Daily',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['kevin-tang', 'tyler-levin'],
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'julia-zhu',
      englishName: 'Julia Zhu',
      gender: 'female',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shannon-tsai', 'jessica-wang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'charley-xia',
      englishName: 'Charley Xia',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['kevin-tang', 'tyler-levin'],
      familyId: 'xia-family',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'moana-xia',
      englishName: 'Moana Xia',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-2'],
      familyId: 'xia-family',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joseph-kuwashima',
      englishName: 'Joseph Kuwashima',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'aquiline-pasipodya',
      englishName: 'Aquiline Pasipodya',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anajah-culmer',
      englishName: 'Anajah Culmer',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'willow-martin',
      englishName: 'Willow Martin',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'nirbisha-mishra',
      englishName: 'Nirbisha Mishra',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'rafi-islam',
      englishName: 'Rafi Islam',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'emily-odell',
      englishName: 'Emily O\'Dell',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ilyc-loten',
      englishName: 'Ilyc Loten',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'noah-kefjin-asfaw',
      englishName: 'Noah Kefjin Asfaw',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'basira-h',
      englishName: 'Basira H',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shefalica-thapa',
      englishName: 'Shefalica Thapa',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alison-tuck',
      englishName: 'Alison Tuck',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yordanos-mekonnen',
      englishName: 'Yordanos Mekonnen',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anna-josephine',
      englishName: 'Anna Josephine',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sydney-blackburn',
      englishName: 'Sydney Blackburn',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jess-aleigha',
      englishName: 'Jess Aleigha',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'seoyeon-kim',
      englishName: 'Seoyeon Kim',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jhadiel-camacho',
      englishName: 'Jhadiel Camacho',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'steel-de-groft',
      englishName: 'Steel De Groft',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'molly-hoover',
      englishName: 'Molly Hoover',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'arlene-odonnell',
      englishName: 'Arlene ODonnell',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alyssa-siehien',
      englishName: 'Alyssa Siehien',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kendrick-rozelle',
      englishName: 'Kendrick Rozelle',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kathy-collins',
      englishName: 'Kathy Collins',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sergio-oneill',
      englishName: 'Sergio ONeill',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'trinity-sailer',
      englishName: 'Trinity Sailer',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'meghan-harlow',
      englishName: 'Meghan Harlow',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'reghan-cutler',
      englishName: 'Reghan Cutler',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lucas-keesee',
      englishName: 'Lucas Keesee',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'becky-liu',
      englishName: 'Becky Liu',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      familyId: 'liu-family',
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'samantha-klotzbach',
      englishName: 'Samantha Klotzbach',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'howie-fang',
      englishName: 'Howie Fang',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joyce-huang',
      englishName: 'Joyce Huang',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shawn-ames',
      englishName: 'Shawn Ames',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['tyler-levin', 'kevin-tang', 'john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zixuan-chen',
      englishName: 'Iris Chen',
      chineseName: 'Zixuan',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'melinda-li', 'shannon-tsai'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'michelle-wang',
      englishName: 'Michelle Wang',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'cole-richards',
      englishName: 'Cole Richards',
      gender: 'male',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'daniel-braswell',
      englishName: 'Daniel Braswell',
      chineseName: 'Dan',
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: ['admin', 'shepherd-1'],
      familyId: 'braswell-family',
      groupIds: ['young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joshua-smith',
      englishName: 'Joshua Smith',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['tyler-levin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sia-brady',
      englishName: 'Sia Brady',
      gender: 'female',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'xena-cosgrove',
      englishName: 'Xena Cosgrove',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['shepherd-2', 'rachel-liu'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'angelina-chen',
      englishName: 'Angelina Chen',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ce-liu',
      englishName: 'Ce Liu',
      gender: 'male',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'milani-gladson',
      englishName: 'Milani Gladson',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'meiqing-wang',
      englishName: 'Meiqing Wang',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bill-cosgrove',
      englishName: 'Bill Cosgrove',
      gender: 'male',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['admin', 'jay-song', 'john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'caitlin-brown',
      englishName: 'Caitlin Brown',
      gender: 'female',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'andrew-schages',
      englishName: 'Andrew Schages',
      gender: 'male',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jaquan-claiborne',
      englishName: 'Jaquan Claiborne',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'beck-johnson',
      englishName: 'Beck Johnson',
      gender: 'female',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zizai-liu',
      englishName: 'Zizai Liu',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['luke-zhang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'peter-macranie',
      englishName: 'Peter MaCranie',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['luke-zhang', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sara-ellington-2',
      englishName: 'Sara Ellington',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'roshani-gladson',
      englishName: 'Roshani Gladson',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'dottie-robertson',
      englishName: 'Dottie Robertson',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'hannah-vestal',
      englishName: 'Hannah Vestal',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'benjamin-nguyen',
      englishName: 'Benjamin Nguyen',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jessie-vestal',
      englishName: 'Jessie Vestal',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jenna-bradfield',
      englishName: 'Jenna Bradfield',
      membershipStatus: 'sunday-attendee',
      language: 'english',
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alpha-zhong',
      englishName: 'Alpha Zhong',
      chineseName: 'Yuan',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['david-kao'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'annie-xing',
      englishName: 'Annie Xing',
      chineseName: 'Xuan',
      membershipStatus: 'fellowship-attendee',
      language: 'english',
      assignedShepherdIds: ['melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'luke-zhang',
      englishName: 'Luke Zhang',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      language: 'english',
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
  ],

  families: [
    {
      id: 'cheng-household',
      label: 'Cheng Family',
      tags: [],
      memberIds: ['long-cheng', 'fangyu-ai'],
    },
    {
      id: 'kao-household',
      label: 'Kao Family',
      tags: [],
      memberIds: ['david-kao'],
    },
    {
      id: 'levin-household',
      label: 'Levin Family',
      tags: [],
      memberIds: ['tyler-levin', 'lin-ho'],
    },
    {
      id: 'zhang-household',
      label: 'Zhang Family',
      tags: [],
      memberIds: ['jiade-zhang'],
    },
    {
      id: 'tang-household',
      label: 'Tang Family',
      tags: [],
      memberIds: ['gillian-tang', 'kevin-tang'],
    },
    {
      id: 'eades-family',
      label: 'Eades Family',
      tags: [],
      memberIds: ['daini-eades', 'jacob-eades'],
    },
    {
      id: 'xia-family',
      label: 'Xia Family',
      tags: [],
      memberIds: ['charley-xia', 'moana-xia'],
    },
    {
      id: 'braswell-family',
      label: 'Braswell Family',
      tags: [],
      memberIds: ['anne-park-braswell', 'daniel-braswell'],
    },
    {
      id: 'sparklin-family',
      label: 'Sparklin Family',
      tags: [],
      memberIds: ['miranda-sparklin', 'ryan-sparklin'],
    },
    {
      id: 'liu-family',
      label: 'Liu Family',
      tags: [],
      memberIds: ['qing-liu', 'rachel-liu', 'debbie-liu', 'becky-liu'],
    },
  ],

  groups: [
    {
      id: 'students',
      name: 'Students Fellowship (Chinese)',
      description: 'Our vision is "PALS" — a mixture of Greek and English words. P-phronesis (wisdom/prudence), A-agape (sacrificial love), L-logos (word/truth), S-service/dedication. We help students mature in PALS through weekly small groups, special workshops, and church-related volunteering opportunities with brothers and sisters in small group community.',
      leaderIds: ['david-kao'],
      memberIds: ['xiang-you', 'long-cheng', 'yu-shan-tsai', 'hanping-bao', 'yinong-fang', 'fangyu-ai', 'long-jing', 'mei-li', 'franklin-wang', 'jessica-wang', 'ella-zajonc', 'yingwen-wang', 'xinyi-zhang', 'kuo-zhang', 'jiade-zhang', 'peter-zhuang', 'grace-phillips', 'heidi-allen', 'jubilee-harris', 'david-green', 'mattaniah-wilson', 'person-row-128', 'deborah-liu', 'zach-sun', 'jackson-zakariasen', 'gary-yao', 'shane-wang', 'julia-zhu', 'joseph-kuwashima'],
      relatedFamilyIds: [],
    },
    {
      id: 'life-young-professional',
      name: 'Life / Young Professional',
      description: 'LIFe stands for Lynchburg International Fellowship. We meet weekly for worship, Bible study, and fellowship. Contact the group leader for address. Join our WhatsApp group to stay updated on our weekly meeting agenda.',
      leaderIds: ['lin-ho', 'tyler-levin', 'gillian-tang', 'kevin-tang'],
      memberIds: ['daini-eades', 'asia-brady', 'jacob-eades', 'gillian-tang', 'lin-ho', 'jake-guerrero', 'faith-lang', 'tyler-levin', 'steven-ni', 'brandon-roos', 'miranda-sparklin', 'ryan-sparklin', 'amber-wang', 'kevin-tang', 'charley-xia', 'moana-xia', 'samantha-klotzbach'],
      relatedFamilyIds: [],
    },
    {
      id: 'forest-young-family',
      name: 'Forest Family',
      description: 'We meet weekly for Bible study. This group provides childcare for ages 5–12.',
      leaderIds: ['qing-liu'],
      memberIds: ['zachary-daily', 'lizhi-daily', 'huina-hu', 'yixin-jin', 'rachel-liu', 'yingguang-liu', 'qing-liu', 'zhenying-wang', 'yu-zhou', 'aihua-yi', 'lianjie-xue', 'weilong-zhuo'],
      relatedFamilyIds: [],
    },
    {
      id: 'cornerstone-seniors',
      name: 'Cornerstone / Seniors',
      leaderIds: ['jay-song'],
      memberIds: ['kwan-cheng', 'keimei-chang', 'gordon-goh', 'anna-goh', 'lui-kuong-lai', 'xiaosang-huang', 'jay-song', 'juiying-yu', 'may-zhan'],
      relatedFamilyIds: [],
    },
    {
      id: 'forty-plus-seniors',
      name: '40+ / Seniors',
      leaderIds: ['john-thompson'],
      memberIds: ['harmon-blanding', 'janette-blanding', 'jack-kerns', 'brenda-kerns', 'jennifer-mariner', 'mark-miller', 'vicki-miller', 'iona-nixon', 'shawn-thompson', 'john-thompson'],
      relatedFamilyIds: [],
    },
    {
      id: 'seekers',
      name: 'Seekers',
      leaderIds: [],
      memberIds: ['eva-brooks', 'diane-francis', 'faye-gallier', 'sandra-west'],
      relatedFamilyIds: [],
    },
    {
      id: 'men',
      name: "Men's Group (Chinese)",
      description: 'Read books to know Christ more!',
      leaderIds: [],
      memberIds: ['james-forbes'],
      relatedFamilyIds: [],
    },
    {
      id: 'youth',
      name: 'Youth',
      leaderIds: ['lin-ho', 'tyler-levin', 'gillian-tang'],
      memberIds: ['debbie-liu', 'bekkah-shi', 'gabriel-daily', 'becky-liu'],
      relatedFamilyIds: [],
    },
    {
      id: 'young-family-group',
      name: 'Young Family Group',
      leaderIds: ['long-cheng'],
      memberIds: ['long-cheng', 'fangyu-ai', 'daini-eades', 'jacob-eades', 'anne-park-braswell', 'daniel-braswell', 'miranda-sparklin', 'ryan-sparklin'],
      relatedFamilyIds: ['cheng-household', 'eades-family', 'braswell-family', 'sparklin-family'],
    },
  ],

  notes: [
    // ── Long Cheng (shepherd-1) logs ───────────────────────────────────────
    {
      id: 'note-1',
      personId: 'xiang-you',
      type: 'check-in',
      visibility: 'private',
      content: `Caught up with Bob after Sunday service. He seems to be settling in well — started attending the students group regularly. Mentioned he's been feeling some pressure with grad school deadlines. Encouraged him to stay connected.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(3),
    },
    {
      id: 'note-2',
      personId: 'daini-eades',
      type: 'prayer-request',
      visibility: 'private',
      content: `Daini reached out over WeChat. She and Jacob are navigating a difficult season — Jacob is between jobs and they're feeling the financial strain. Asked for prayer for wisdom and provision. Will follow up in person next week.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(7),
    },
    {
      id: 'note-3',
      personId: 'fangyu-ai',
      type: 'check-in',
      visibility: 'private',
      content: `Brief check-in with Fangyu on WeChat. She's been adjusting well to the new city. Mentioned she misses her family back home but finds the young family group really welcoming. Encouraged her to keep coming.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(14),
    },
    {
      id: 'note-4',
      personId: 'ryan-sparklin',
      type: 'general',
      visibility: 'private',
      content: `Called Ryan to check in. He and Miranda just had their second child — everyone is healthy! They're a bit overwhelmed with the newborn and a toddler but in good spirits. Offered to organize a meal train through the group.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(6),
    },
    {
      id: 'note-5',
      personId: 'jacob-eades',
      type: 'prayer-request',
      visibility: 'public',
      content: 'Jacob came to me after service and opened up about the job search. He has two promising interviews next week. Prayed together. He appreciated it. Will keep checking in.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(2),
    },
    {
      id: 'note-6',
      personId: 'anne-park-braswell',
      type: 'check-in',
      visibility: 'private',
      content: `Texted Anne to see how she's doing. She's been busy with work and the kids' schedules but appreciated the message. Said she and Daniel are planning to attend the Young Family Group retreat.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(10),
    },
    {
      id: 'note-7',
      personId: 'zach-sun',
      type: 'event',
      visibility: 'public',
      content: 'Met Zach at the church picnic. First time seeing him since he started attending. He seemed quiet but engaged. Introduced him to a few others in the students group. Will make a point to connect more intentionally.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(21),
    },
    {
      id: 'note-8',
      familyId: 'eades-family',
      type: 'event',
      visibility: 'private',
      content: 'Had the Eades family over for dinner with two other young families. Great time of fellowship. The kids played together. Jacob and Daini opened up more in this setting — feeling more like they belong.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(18),
    },

    // ── Asia Brady (shepherd-2) logs ───────────────────────────────────────
    {
      id: 'note-9',
      personId: 'gillian-tang',
      type: 'check-in',
      visibility: 'private',
      content: `Had coffee with Gillian after Wednesday prayer meeting. She's doing really well — very involved in the worship team. Mentioned she's been thinking about deeper Bible study and is considering joining the discipleship track.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(2),
    },
    {
      id: 'note-10',
      personId: 'moana-xia',
      type: 'prayer-request',
      visibility: 'private',
      content: `Moana called, quite distressed. She's been struggling with loneliness since moving here from the Bay Area. Her parents are also going through some health issues back home. Prayed with her on the phone. Plan to introduce her to a few more women in the group.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(10),
    },
    {
      id: 'note-11',
      personId: 'lin-ho',
      type: 'prayer-request',
      visibility: 'private',
      content: 'Lisa messaged asking for prayer for her marriage — she and Tyler have been going through a rough patch. She seemed hesitant to share details but wanted someone to know. Encouraged her to consider speaking with Pastor Qing together. Praying for them.',
      createdBy: 'shepherd-2',
      createdAt: daysAgo(5),
    },
    {
      id: 'note-12',
      personId: 'ella-zajonc',
      type: 'check-in',
      visibility: 'private',
      content: `Texted Ella to check in — she missed the last two Sundays. She replied that she'd been traveling for work. Seems fine, just busy. Will follow up if she misses again.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(8),
    },
    {
      id: 'note-13',
      personId: 'natalie-cummings',
      type: 'general',
      visibility: 'private',
      content: `Natalie mentioned she's interested in getting baptized. She said she's been a believer for years but never took the step formally. Pointed her toward the membership class and will loop in Pastor Qing.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(15),
    },
    {
      id: 'note-14',
      personId: 'jessica-wang',
      type: 'check-in',
      visibility: 'public',
      content: `Good conversation with Jessica at the women's event. She's recently started a new job and loves it. Also mentioned she's been reading through the New Testament on her own — encouraged her.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(30),
    },
    {
      id: 'note-15',
      personId: 'gillian-tang',
      type: 'check-in',
      visibility: 'private',
      content: `Checked in via text before the holidays. Gillian said she's heading home to see family — asked for prayer for some family tension she anticipates. Will follow up when she returns.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(35),
    },

    // ── Admin (Pastor Qing) logs ────────────────────────────────────────────
    {
      id: 'note-16',
      personId: 'long-cheng',
      type: 'general',
      visibility: 'private',
      content: `Met with Long over lunch to review how his group is doing. He's handling things well but mentioned feeling stretched with his own life responsibilities. Encouraged him, reminded him shepherding is about relationship, not performance.`,
      createdBy: 'admin',
      createdAt: daysAgo(1),
    },
    {
      id: 'note-17',
      personId: 'tyler-levin',
      type: 'prayer-request',
      visibility: 'private',
      content: `Tyler pulled me aside after service. He and Lisa have been having some tension at home. He mentioned feeling disconnected from the church community. Asked for prayer and for some pastoral guidance. We'll meet for coffee next week.`,
      createdBy: 'admin',
      createdAt: daysAgo(4),
    },
    {
      id: 'note-18',
      personId: 'mark-miller',
      type: 'check-in',
      visibility: 'private',
      content: `Called Mark. He and Vicki have been faithful attendees. He mentioned they'd love to see more seniors get connected. We discussed the idea of a 40+ social event in the spring.`,
      createdBy: 'admin',
      createdAt: daysAgo(9),
    },
    {
      id: 'note-19',
      personId: 'rachel-liu',
      type: 'check-in',
      visibility: 'private',
      content: `Checked in with Rachel on WeChat. She's been coming consistently since transferring from another church. Seems eager to serve but still finding her footing. Suggested she connect with the welcome team.`,
      createdBy: 'admin',
      createdAt: daysAgo(12),
    },
    {
      id: 'note-20',
      personId: 'eric-chen',
      type: 'event',
      visibility: 'public',
      content: 'Eric shared his testimony at the membership class — very moving. He credited the student group for helping him through a difficult time in his faith. The whole class was encouraged.',
      createdBy: 'admin',
      createdAt: daysAgo(25),
    },
  ],

  todos: [
    // ── Long Cheng (shepherd-1) todos ──────────────────────────────────────
    {
      id: 'todo-1',
      personId: 'daini-eades',
      title: `Follow up with Daini about Jacob's job situation`,
      dueDate: daysAhead(1),
      alert: '1day',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(7),
    },
    {
      id: 'todo-2',
      personId: 'xiang-you',
      title: 'Check in with Bob after grad school deadline',
      dueDate: daysAhead(3),
      alert: 'none',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(3),
    },
    {
      id: 'todo-3',
      personId: 'ryan-sparklin',
      title: 'Organize meal train for Sparklin family (new baby)',
      dueDate: daysAhead(2),
      alert: '1day',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(6),
    },
    {
      id: 'todo-4',
      personId: 'jacob-eades',
      title: 'Send Jacob encouragement before his job interviews',
      dueDate: daysAhead(0),
      alert: 'on-time',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(2),
    },
    {
      id: 'todo-5',
      personId: 'fangyu-ai',
      title: 'Monthly check-in with Fangyu',
      dueDate: daysAhead(7),
      alert: 'none',
      repeat: 'monthly',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(14),
    },
    {
      id: 'todo-6',
      personId: 'anne-park-braswell',
      title: 'Confirm Anne & Daniel are coming to the Young Family retreat',
      dueDate: daysAgo(0),
      alert: 'none',
      repeat: 'none',
      completed: true,
      completedAt: daysAgo(1),
      createdBy: 'shepherd-1',
      createdAt: daysAgo(10),
    },
    {
      id: 'todo-7',
      personId: 'zach-sun',
      title: 'Grab coffee with Zach — get to know him better',
      dueDate: daysAhead(10),
      alert: '1day',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(21),
    },

    // ── Asia Brady (shepherd-2) todos ──────────────────────────────────────
    {
      id: 'todo-8',
      personId: 'moana-xia',
      title: 'Introduce Moana to 2–3 women in the Life / YP group',
      dueDate: daysAhead(4),
      alert: '1day',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(10),
    },
    {
      id: 'todo-9',
      personId: 'lin-ho',
      title: 'Follow up with Lisa — check how things are at home',
      dueDate: daysAhead(2),
      alert: 'none',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(5),
    },
    {
      id: 'todo-10',
      personId: 'natalie-cummings',
      title: 'Connect Natalie with Pastor Qing re: baptism interest',
      dueDate: daysAhead(5),
      alert: 'none',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(15),
    },
    {
      id: 'todo-11',
      personId: 'gillian-tang',
      title: 'Welcome Gillian back from family visit',
      dueDate: daysAhead(0),
      alert: 'on-time',
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(35),
    },
    {
      id: 'todo-12',
      personId: 'ella-zajonc',
      title: 'Check if Ella is back from her work travel',
      dueDate: daysAgo(1),
      alert: 'none',
      repeat: 'none',
      completed: true,
      completedAt: daysAgo(1),
      createdBy: 'shepherd-2',
      createdAt: daysAgo(8),
    },
    {
      id: 'todo-13',
      personId: 'leanne-hanson',
      title: `Leanne's birthday`,
      dueDate: daysAhead(6),
      alert: '1day',
      repeat: 'yearly',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(60),
    },

    // ── Admin (Pastor Qing) todos ───────────────────────────────────────────
    {
      id: 'todo-14',
      personId: 'tyler-levin',
      title: 'Coffee with Tyler — pastoral follow-up',
      dueDate: daysAhead(5),
      alert: '1hour',
      repeat: 'none',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(4),
    },
    {
      id: 'todo-15',
      personId: 'long-cheng',
      title: 'Monthly shepherd check-in with Long',
      dueDate: daysAhead(14),
      alert: 'none',
      repeat: 'monthly',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(1),
    },
    {
      id: 'todo-16',
      personId: 'rachel-liu',
      title: 'Follow up with Rachel about joining Welcome Team',
      dueDate: daysAhead(7),
      alert: 'none',
      repeat: 'none',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(12),
    },
    {
      id: 'todo-17',
      personId: 'mark-miller',
      title: 'Plan spring social event for 40+ group with Mark',
      dueDate: daysAhead(21),
      alert: 'none',
      repeat: 'none',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(9),
    },
    {
      id: 'todo-18',
      personId: 'eric-chen',
      title: `Check in with Eric — see how he's doing post-testimony`,
      dueDate: daysAgo(3),
      alert: 'none',
      repeat: 'none',
      completed: true,
      completedAt: daysAgo(3),
      createdBy: 'admin',
      createdAt: daysAgo(25),
    },
  ],
};

