import { addDays, subDays, formatISO } from 'date-fns';
import { type AppData } from './types';

function daysAgo(n: number): string {
  return formatISO(subDays(new Date(), n));
}

function daysAhead(n: number): string {
  return formatISO(addDays(new Date(), n));
}

export const initialData: AppData = {
  personas: [
    {
      id: 'admin',
      name: 'Pastor Paul Liu',
      role: 'admin',
      personId: 'qing-liu',
      assignedPeopleIds: [
        'long-cheng',
        'zachary-daily',
        'lizhi-daily',
        'yinong-fang',
        'jacob-eades',
        'jake-guerrero',
        'tyler-levin',
        'rachel-liu',
        'yingguang-liu',
        'tom-mullett',
        'mark-miller',
        'steven-ni',
        'chris-nixon',
        'vicki-miller',
        'jay-song',
        'john-thompson',
        'zhenying-wang',
        'aihua-yi',
        'weilong-zhuo',
        'peter-zhuang',
        'lujia-yin',
        'zach-sun',
        'blake-levin',
        'eric-chen',
        'daniel-braswell',
        'bill-cosgrove',
      ],
    },
    {
      id: 'shepherd-1',
      name: 'Long Cheng',
      role: 'shepherd',
      personId: 'long-cheng',
      assignedPeopleIds: [
        'xiang-you',
        'daini-eades',
        'fangyu-ai',
        'jacob-eades',
        'miranda-sparklin',
        'ryan-sparklin',
        'yu-ren-liu',
        'anne-park-braswell',
        'david-green',
        'mattaniah-wilson',
        'zach-sun',
        'eric-chen',
        'joseph-kuwashima',
        'zixuan-chen',
        'michelle-wang',
        'cole-richards',
        'daniel-braswell',
        'angelina-chen',
        'ce-liu',
        'peter-macranie',
      ],
    },
    {
      id: 'shepherd-2',
      name: 'Asia Brady',
      role: 'shepherd',
      personId: 'asia-brady',
      assignedPeopleIds: [
        'moana-xia',
        'gillian-tang',
        'lin-ho',
        'mei-li',
        'marni-thompson',
        'miranda-sparklin',
        'jessica-wang',
        'ella-zajonc',
        'leanne-hanson',
        'natalie-cummings',
        'xena-cosgrove',
      ],
    },
    {
      id: 'welcome-team',
      name: 'Welcome Team',
      role: 'welcome-team',
      personId: 'miranda-sparklin',
      assignedPeopleIds: [],
    },
  ],

  people: [
    {
      id: 'xiang-you',
      preferredName: 'Bob',
      lastName: 'You',
      alternativeName: 'Xiang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['david-kao', 'shepherd-1'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'long-cheng',
      preferredName: 'Long',
      lastName: 'Cheng',
      gender: 'male',
      isShepherd: true,
      appRole: 'shepherd' as const,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      familyId: 'cheng-household',
      groupIds: ['students', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'david-kao',
      preferredName: 'David',
      lastName: 'Kao',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['luke-zhang', 'shannon-tsai'],
      familyId: 'kao-household',
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yu-shan-tsai',
      preferredName: 'Yu-Shan',
      lastName: 'Tsai',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['david-kao', 'melinda-li'],
      familyId: 'kao-household',
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'harmon-blanding',
      preferredName: 'Harmon',
      lastName: 'Blanding',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bonnie-drumheller',
      preferredName: 'Bonnie',
      lastName: 'Drumheller',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'eva-brooks',
      preferredName: 'Eva',
      lastName: 'Brooks',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'janette-blanding',
      preferredName: 'Janette',
      lastName: 'Blanding',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kwan-cheng',
      preferredName: 'Sonia',
      lastName: 'Cheng',
      alternativeName: 'Kwan',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zachary-daily',
      preferredName: 'Zachary',
      lastName: 'Daily',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lyle-brooks',
      preferredName: 'Pete',
      lastName: 'Brooks',
      alternativeName: 'Lyle',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jimmy-cash',
      preferredName: 'Jimmy',
      lastName: 'Cash (passed away)',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'phyllis-cash',
      preferredName: 'Phyllis',
      lastName: 'Cash',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lizhi-daily',
      preferredName: 'Lizhi',
      lastName: 'Daily',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'hanping-bao',
      preferredName: 'Hanping',
      lastName: 'Bao',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yinong-fang',
      preferredName: 'Yinong',
      lastName: 'Fang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'daini-eades',
      preferredName: 'Daini',
      lastName: 'Eades',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1'],
      familyId: 'eades-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'asia-brady',
      preferredName: 'Asia',
      lastName: 'Brady',
      gender: 'female',
      isShepherd: true,
      appRole: 'shepherd' as const,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'keimei-chang',
      preferredName: 'KeiMei',
      lastName: 'Chang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'fangyu-ai',
      preferredName: 'Fangyu',
      lastName: 'Ai',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      familyId: 'cheng-household',
      groupIds: ['students', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'james-forbes',
      preferredName: 'James',
      lastName: 'Forbes',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['men'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'diane-francis',
      preferredName: 'Diane',
      lastName: 'Francis',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jacob-eades',
      preferredName: 'Jacob',
      lastName: 'Eades',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'admin'],
      familyId: 'eades-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'faye-gallier',
      preferredName: 'Faye',
      lastName: 'Gallier',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gordon-goh',
      preferredName: 'Gordon',
      lastName: 'Goh',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anna-goh',
      preferredName: 'Anna',
      lastName: 'Goh',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'long-jing',
      preferredName: 'James',
      lastName: 'Jing',
      alternativeName: 'Long',
      gender: 'male',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'huina-hu',
      preferredName: 'Huina',
      lastName: 'Hu',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gillian-tang',
      preferredName: 'Gillian',
      lastName: 'Tang',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-2'],
      familyId: 'tang-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lui-kuong-lai',
      preferredName: 'Lui',
      lastName: 'Kuong Lai',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lin-ho',
      preferredName: 'Lisa',
      lastName: 'Levin',
      alternativeName: 'Lin Ho',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['gillian-tang', 'shepherd-2'],
      familyId: 'levin-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yixin-jin',
      preferredName: 'Joy',
      lastName: 'Jin',
      alternativeName: 'Yixin',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['kevin-tang', 'lin-ho', 'gillian-tang', 'tyler-levin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jack-kerns',
      preferredName: 'Jack',
      lastName: 'Kerns',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'mei-li',
      preferredName: 'Melinda',
      lastName: 'Li',
      alternativeName: 'Mei',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai', 'shepherd-2'],
      familyId: 'zhang-household',
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jake-guerrero',
      preferredName: 'Jake',
      lastName: 'Guerrero',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'faith-lang',
      preferredName: 'Faith',
      lastName: 'Lang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['lin-ho', 'gillian-tang', 'melinda-li'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'xiaosang-huang',
      preferredName: 'Xiaosang',
      lastName: 'Huang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'tyler-levin',
      preferredName: 'Tyler',
      lastName: 'Levin',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'john-thompson', 'kevin-tang'],
      familyId: 'levin-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'brenda-kerns',
      preferredName: 'Brenda',
      lastName: 'Kerns',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'rachel-liu',
      preferredName: 'Rachel',
      lastName: 'Liu',
      alternativeName: '李金鹤',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      familyId: 'liu-family',
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yingguang-liu',
      preferredName: 'Yingguang',
      lastName: 'Liu',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'tom-mullett',
      preferredName: 'Tom',
      lastName: 'Mullett',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson', 'admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jennifer-mariner',
      preferredName: 'Jennifer',
      lastName: 'Mariner',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'qing-liu',
      preferredName: 'Paul',
      lastName: 'Liu',
      alternativeName: 'Qing',
      gender: 'male',
      isShepherd: true,
      appRole: 'admin' as const,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song', 'john-thompson'],
      familyId: 'liu-family',
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'mark-miller',
      preferredName: 'Mark',
      lastName: 'Miller',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'steven-ni',
      preferredName: 'Steven',
      lastName: 'Ni',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['kevin-tang', 'tyler-levin', 'admin'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'chris-nixon',
      preferredName: 'Chris',
      lastName: 'Nixon',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson', 'admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'karen-nixon',
      preferredName: 'Karen',
      lastName: 'Nixon',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'brandon-roos',
      preferredName: 'Brandon',
      lastName: 'Roos',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'marni-thompson',
      preferredName: 'Marni',
      lastName: 'Thompson',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson', 'shepherd-2'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'vicki-miller',
      preferredName: 'Vicki',
      lastName: 'Miller',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'franklin-wang',
      preferredName: 'Franklin',
      lastName: 'Wang',
      gender: 'male',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['david-kao'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'iona-nixon',
      preferredName: 'Iona',
      lastName: 'Nixon',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'miranda-sparklin',
      preferredName: 'Miranda',
      lastName: 'Sparklin',
      appRole: 'welcome-team' as const,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'shepherd-2'],
      familyId: 'sparklin-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jessica-wang',
      preferredName: 'Jessica',
      lastName: 'Wang',
      alternativeName: 'Huijin',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['melinda-li', 'shepherd-2', 'shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ryan-sparklin',
      preferredName: 'Ryan',
      lastName: 'Sparklin',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['kevin-tang', 'tyler-levin', 'shepherd-1'],
      familyId: 'sparklin-family',
      groupIds: ['life-young-professional', 'young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shawn-thompson',
      preferredName: 'Shawn',
      lastName: 'Thompson',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jay-song',
      preferredName: 'Jay',
      lastName: 'Song',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'john-thompson'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'john-thompson',
      preferredName: 'John',
      lastName: 'Thompson',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song', 'admin'],
      groupIds: ['forty-plus-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sandra-west',
      preferredName: 'Sandra',
      lastName: 'West',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: ['seekers'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'amber-wang',
      preferredName: 'Amber',
      lastName: 'Wang',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zhenying-wang',
      preferredName: 'Zhenying',
      lastName: 'Wang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'rachel-liu'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'juiying-yu',
      preferredName: 'Juiying',
      lastName: 'Yu',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ella-zajonc',
      preferredName: 'Ella',
      lastName: 'Zajonc',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai', 'shepherd-2', 'melinda-li'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yingwen-wang',
      preferredName: 'Wendy',
      lastName: 'Wang',
      alternativeName: 'Yingwen',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yu-zhou',
      preferredName: 'Yu',
      lastName: 'Zhou',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'xinyi-zhang',
      preferredName: 'Xinyi',
      lastName: 'Zhang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['melinda-li', 'shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'may-zhan',
      preferredName: 'May',
      lastName: 'Zhan',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jay-song'],
      groupIds: ['cornerstone-seniors'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kuo-zhang',
      preferredName: 'Jonathan',
      lastName: 'Zhang',
      alternativeName: 'Kuo',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: ['kevin-tang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'aihua-yi',
      preferredName: 'Aihua',
      lastName: 'Yi',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lianjie-xue',
      preferredName: 'Lianjie',
      lastName: 'Xue',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jiade-zhang',
      preferredName: 'Jiade',
      lastName: 'Zhang',
      gender: 'male',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['david-kao'],
      familyId: 'zhang-household',
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'weilong-zhuo',
      preferredName: 'Weilong',
      lastName: 'Zhuo',
      gender: 'male',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: ['forest-young-family'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'peter-zhuang',
      preferredName: 'Peter',
      lastName: 'Zhuang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['david-kao', 'admin'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'adoniah',
      preferredName: 'Adoniah',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bekah',
      preferredName: 'Bekah',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'evie-jang',
      preferredName: 'Evie',
      lastName: 'Jang',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      isBeingDiscipled: true,
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'christine',
      preferredName: 'Christine',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'hyeonyin',
      preferredName: 'Hyeonyin',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'david',
      preferredName: 'David',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'grant',
      preferredName: 'Grant',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jack-donohue',
      preferredName: 'Jack',
      lastName: 'Donohue',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(4),
    },
    {
      id: 'emily',
      preferredName: 'Emily',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'esther',
      preferredName: 'Esther',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'elisa-garcia',
      preferredName: 'Elisa',
      lastName: 'Garcia',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(8),
    },
    {
      id: 'cameron',
      preferredName: 'Cameron',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'izzy-dreisilker',
      preferredName: 'Izzy',
      lastName: 'Dreisilker',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'conghoon-choi',
      preferredName: 'Conghoon',
      lastName: 'Choi',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(2),
    },
    {
      id: 'andrew-g',
      preferredName: 'Andrew',
      lastName: 'G',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'emily-hadden',
      preferredName: 'Emily',
      lastName: 'Hadden',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ariana',
      preferredName: 'Ariana',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'harrel',
      preferredName: 'Harrel',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jadon',
      preferredName: 'Jadon',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yu-ren-liu',
      preferredName: 'Josh',
      lastName: 'Liu',
      alternativeName: 'Yu Ren',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jonathan',
      preferredName: 'Jonathan',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'melissa',
      preferredName: 'Melissa',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joslyn',
      preferredName: 'Joslyn',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lujia-yin',
      preferredName: 'Lujia',
      lastName: 'Yin',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'leah-morgan',
      preferredName: 'Leah',
      lastName: 'Morgan',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kellyn-hale',
      preferredName: 'Kellyn',
      lastName: 'Hale',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kristiana-underwood',
      preferredName: 'Kristiana',
      lastName: 'Underwood',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'natalia',
      preferredName: 'Natalia',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'nicholas',
      preferredName: 'Nicholas',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'luca-walton',
      preferredName: 'Luca',
      lastName: 'Walton',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'keeley-sheppard',
      preferredName: 'Keeley',
      lastName: 'Sheppard',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'marcos',
      preferredName: 'Marcos',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zach-mcclanrance',
      preferredName: 'Zach',
      lastName: 'Mcclanrance',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sara-ellington',
      preferredName: 'Sara',
      lastName: 'Ellington',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'soohyeon-cho',
      preferredName: 'Soohyeon',
      lastName: 'Cho',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'umairli',
      preferredName: 'Umairli',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'timeea',
      preferredName: 'Timeea',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sergio',
      preferredName: 'Sergio',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sara-xavier',
      preferredName: 'Sara',
      lastName: 'Xavier',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'seobeen',
      preferredName: 'Seobeen',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'daiwei-huang',
      preferredName: 'Daiwei',
      lastName: 'Huang',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['charley-xia'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anne-park-braswell',
      preferredName: 'Anne',
      lastName: 'Park-Braswell',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1'],
      familyId: 'braswell-family',
      groupIds: ['young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'grace-phillips',
      preferredName: 'Grace',
      lastName: 'Phillips',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'elisabeth-grace-goode',
      preferredName: 'Elisabeth',
      lastName: 'Grace Goode',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'heidi-allen',
      preferredName: 'Heidi',
      lastName: 'Allen',
      gender: 'female',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['melinda-li'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jubilee-harris',
      preferredName: 'Jubilee',
      lastName: 'Harris',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'david-green',
      preferredName: 'David',
      lastName: 'Green',
      gender: 'male',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'mattaniah-wilson',
      preferredName: 'Mattaniah',
      lastName: 'Wilson',
      membershipStatus: 'membership-track',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'chase-cartwright',
      preferredName: 'Chase',
      lastName: 'Cartwright',
      membershipStatus: 'membership-track',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['moana-xia', 'charley-xia'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kaiya-west',
      preferredName: 'Kaiya',
      lastName: 'West',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'person-row-128',
      preferredName: '家昊',
      lastName: '崔',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['david-kao'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'deborah-liu',
      preferredName: 'Deborah',
      lastName: 'Liu',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai', 'melinda-li'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jessica-fang',
      preferredName: 'Jessica',
      lastName: 'Fang',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai', 'melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alaina-sefiane',
      preferredName: 'Alaina',
      lastName: 'Sefiane',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zach-sun',
      preferredName: 'Zach',
      lastName: 'Sun',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'shepherd-1'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jackson-zakariasen',
      preferredName: 'Jackson',
      lastName: 'Zakariasen',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kevin-tang',
      preferredName: 'Kevin',
      lastName: 'Tang',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['tyler-levin'],
      familyId: 'tang-household',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lu-chang',
      preferredName: 'Lu',
      lastName: 'Chang',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'debbie-liu',
      preferredName: 'Debbie',
      lastName: 'Liu',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['lin-ho', 'gillian-tang'],
      familyId: 'liu-family',
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gary-yao',
      preferredName: 'Gary',
      lastName: 'Yao',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['david-kao', 'luke-zhang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'blake-levin',
      preferredName: 'Blake',
      lastName: 'Levin',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson', 'admin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'eric-chen',
      preferredName: 'Eric',
      lastName: 'Chen',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bekkah-shi',
      preferredName: 'Bekkah',
      lastName: 'Shi',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'leanne-hanson',
      preferredName: 'Leanne',
      lastName: 'Hanson',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-2', 'john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shane-wang',
      preferredName: 'Shane',
      lastName: 'Wang',
      membershipStatus: 'non-member',
      churchAttendance: 'archived',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'boaz-mao',
      preferredName: 'Boaz',
      lastName: 'Mao',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'cavanaugh-oleary',
      preferredName: 'Cavanaugh',
      lastName: 'Oleary',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'natalie-cummings',
      preferredName: 'Natalie',
      lastName: 'Cummings',
      membershipStatus: 'membership-track',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['moana-xia', 'shepherd-2'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'gabriel-daily',
      preferredName: 'Gabriel',
      lastName: 'Daily',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['kevin-tang', 'tyler-levin'],
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'julia-zhu',
      preferredName: 'Julia',
      lastName: 'Zhu',
      gender: 'female',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shannon-tsai', 'jessica-wang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'charley-xia',
      preferredName: 'Charley',
      lastName: 'Xia',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['kevin-tang', 'tyler-levin'],
      familyId: 'xia-family',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'moana-xia',
      preferredName: 'Moana',
      lastName: 'Xia',
      gender: 'female',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-2'],
      familyId: 'xia-family',
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joseph-kuwashima',
      preferredName: 'Joseph',
      lastName: 'Kuwashima',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: ['students'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'aquiline-pasipodya',
      preferredName: 'Aquiline',
      lastName: 'Pasipodya',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anajah-culmer',
      preferredName: 'Anajah',
      lastName: 'Culmer',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'willow-martin',
      preferredName: 'Willow',
      lastName: 'Martin',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'nirbisha-mishra',
      preferredName: 'Nirbisha',
      lastName: 'Mishra',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'rafi-islam',
      preferredName: 'Rafi',
      lastName: 'Islam',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'emily-odell',
      preferredName: 'Emily',
      lastName: "O'Dell",
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ilyc-loten',
      preferredName: 'Ilyc',
      lastName: 'Loten',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'noah-kefjin-asfaw',
      preferredName: 'Noah',
      lastName: 'Kefjin Asfaw',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'basira-h',
      preferredName: 'Basira',
      lastName: 'H',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shefalica-thapa',
      preferredName: 'Shefalica',
      lastName: 'Thapa',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alison-tuck',
      preferredName: 'Alison',
      lastName: 'Tuck',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'yordanos-mekonnen',
      preferredName: 'Yordanos',
      lastName: 'Mekonnen',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'anna-josephine',
      preferredName: 'Anna',
      lastName: 'Josephine',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sydney-blackburn',
      preferredName: 'Sydney',
      lastName: 'Blackburn',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jess-aleigha',
      preferredName: 'Jess',
      lastName: 'Aleigha',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'seoyeon-kim',
      preferredName: 'Seoyeon',
      lastName: 'Kim',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jhadiel-camacho',
      preferredName: 'Jhadiel',
      lastName: 'Camacho',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'steel-de-groft',
      preferredName: 'Steel',
      lastName: 'De Groft',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'molly-hoover',
      preferredName: 'Molly',
      lastName: 'Hoover',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'arlene-odonnell',
      preferredName: 'Arlene',
      lastName: 'ODonnell',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alyssa-siehien',
      preferredName: 'Alyssa',
      lastName: 'Siehien',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kendrick-rozelle',
      preferredName: 'Kendrick',
      lastName: 'Rozelle',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'kathy-collins',
      preferredName: 'Kathy',
      lastName: 'Collins',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sergio-oneill',
      preferredName: 'Sergio',
      lastName: 'ONeill',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'trinity-sailer',
      preferredName: 'Trinity',
      lastName: 'Sailer',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'meghan-harlow',
      preferredName: 'Meghan',
      lastName: 'Harlow',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'reghan-cutler',
      preferredName: 'Reghan',
      lastName: 'Cutler',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'lucas-keesee',
      preferredName: 'Lucas',
      lastName: 'Keesee',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'becky-liu',
      preferredName: 'Becky',
      lastName: 'Liu',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      familyId: 'liu-family',
      groupIds: ['youth'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'samantha-klotzbach',
      preferredName: 'Samantha',
      lastName: 'Klotzbach',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      groupIds: ['life-young-professional'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'howie-fang',
      preferredName: 'Howie',
      lastName: 'Fang',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joyce-huang',
      preferredName: 'Joyce',
      lastName: 'Huang',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['gillian-tang', 'lin-ho'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'shawn-ames',
      preferredName: 'Shawn',
      lastName: 'Ames',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['tyler-levin', 'kevin-tang', 'john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zixuan-chen',
      preferredName: 'Iris',
      lastName: 'Chen',
      alternativeName: 'Zixuan',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'melinda-li', 'shannon-tsai'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'michelle-wang',
      preferredName: 'Michelle',
      lastName: 'Wang',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'cole-richards',
      preferredName: 'Cole',
      lastName: 'Richards',
      gender: 'male',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'daniel-braswell',
      preferredName: 'Dan',
      lastName: 'Braswell',
      alternativeName: 'Daniel',
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'shepherd-1'],
      familyId: 'braswell-family',
      groupIds: ['young-family-group'],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'joshua-smith',
      preferredName: 'Joshua',
      lastName: 'Smith',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['tyler-levin'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sia-brady',
      preferredName: 'Sia',
      lastName: 'Brady',
      gender: 'female',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'xena-cosgrove',
      preferredName: 'Xena',
      lastName: 'Cosgrove',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['shepherd-2', 'rachel-liu'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'angelina-chen',
      preferredName: 'Angelina',
      lastName: 'Chen',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'ce-liu',
      preferredName: 'Ce',
      lastName: 'Liu',
      gender: 'male',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['shepherd-1', 'luke-zhang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'milani-gladson',
      preferredName: 'Milani',
      lastName: 'Gladson',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'meiqing-wang',
      preferredName: 'Meiqing',
      lastName: 'Wang',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'bill-cosgrove',
      preferredName: 'Bill',
      lastName: 'Cosgrove',
      gender: 'male',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['admin', 'jay-song', 'john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'caitlin-brown',
      preferredName: 'Caitlin',
      lastName: 'Brown',
      gender: 'female',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'andrew-schages',
      preferredName: 'Andrew',
      lastName: 'Schages',
      gender: 'male',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jaquan-claiborne',
      preferredName: 'Jaquan',
      lastName: 'Claiborne',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'beck-johnson',
      preferredName: 'Beck',
      lastName: 'Johnson',
      gender: 'female',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'zizai-liu',
      preferredName: 'Zizai',
      lastName: 'Liu',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['luke-zhang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'peter-macranie',
      preferredName: 'Peter',
      lastName: 'MaCranie',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['luke-zhang', 'shepherd-1'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'sara-ellington-2',
      preferredName: 'Sara',
      lastName: 'Ellington',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'roshani-gladson',
      preferredName: 'Roshani',
      lastName: 'Gladson',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'dottie-robertson',
      preferredName: 'Dottie',
      lastName: 'Robertson',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['john-thompson'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'hannah-vestal',
      preferredName: 'Hannah',
      lastName: 'Vestal',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'benjamin-nguyen',
      preferredName: 'Benjamin',
      lastName: 'Nguyen',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jessie-vestal',
      preferredName: 'Jessie',
      lastName: 'Vestal',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'jenna-bradfield',
      preferredName: 'Jenna',
      lastName: 'Bradfield',
      membershipStatus: 'non-member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: ['jessica-wang'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'alpha-zhong',
      preferredName: 'Alpha',
      lastName: 'Zhong',
      alternativeName: 'Yuan',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['david-kao'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'annie-xing',
      preferredName: 'Annie',
      lastName: 'Xing',
      alternativeName: 'Xuan',
      membershipStatus: 'non-member',
      churchAttendance: 'fellowship-group-only',
      language: ['English'],
      assignedShepherdIds: ['melinda-li'],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
    {
      id: 'luke-zhang',
      preferredName: 'Luke',
      lastName: 'Zhang',
      gender: 'male',
      isShepherd: true,
      membershipStatus: 'member',
      churchAttendance: 'regular',
      language: ['English'],
      assignedShepherdIds: [],
      groupIds: [],
      followUpFrequencyDays: 14,
      createdAt: daysAgo(365),
    },
  ],

  families: [
    {
      id: 'cheng-household',
      label: 'Cheng Family',
      tags: [],
      memberIds: ['long-cheng', 'fangyu-ai'],
    },
    {
      id: 'kao-household',
      label: 'Kao Family',
      tags: [],
      memberIds: ['david-kao'],
    },
    {
      id: 'levin-household',
      label: 'Levin Family',
      tags: [],
      memberIds: ['tyler-levin', 'lin-ho'],
    },
    {
      id: 'zhang-household',
      label: 'Zhang Family',
      tags: [],
      memberIds: ['jiade-zhang'],
    },
    {
      id: 'tang-household',
      label: 'Tang Family',
      tags: [],
      memberIds: ['gillian-tang', 'kevin-tang'],
    },
    {
      id: 'eades-family',
      label: 'Eades Family',
      tags: [],
      memberIds: ['daini-eades', 'jacob-eades'],
    },
    {
      id: 'xia-family',
      label: 'Xia Family',
      tags: [],
      memberIds: ['charley-xia', 'moana-xia'],
    },
    {
      id: 'braswell-family',
      label: 'Braswell Family',
      tags: [],
      memberIds: ['anne-park-braswell', 'daniel-braswell'],
    },
    {
      id: 'sparklin-family',
      label: 'Sparklin Family',
      tags: [],
      memberIds: ['miranda-sparklin', 'ryan-sparklin'],
    },
    {
      id: 'liu-family',
      label: 'Liu Family',
      tags: [],
      memberIds: ['qing-liu', 'rachel-liu', 'debbie-liu', 'becky-liu'],
    },
  ],

  groups: [
    {
      id: 'students',
      name: 'Students Fellowship (Chinese)',
      description:
        'Our vision is "PALS" — a mixture of Greek and English words. P-phronesis (wisdom/prudence), A-agape (sacrificial love), L-logos (word/truth), S-service/dedication. We help students mature in PALS through weekly small groups, special workshops, and church-related volunteering opportunities with brothers and sisters in small group community.',
      leaderIds: ['david-kao'],
      memberIds: [
        'xiang-you',
        'long-cheng',
        'yu-shan-tsai',
        'hanping-bao',
        'yinong-fang',
        'fangyu-ai',
        'long-jing',
        'mei-li',
        'franklin-wang',
        'jessica-wang',
        'ella-zajonc',
        'yingwen-wang',
        'xinyi-zhang',
        'kuo-zhang',
        'jiade-zhang',
        'peter-zhuang',
        'grace-phillips',
        'heidi-allen',
        'jubilee-harris',
        'david-green',
        'mattaniah-wilson',
        'person-row-128',
        'deborah-liu',
        'zach-sun',
        'jackson-zakariasen',
        'gary-yao',
        'shane-wang',
        'julia-zhu',
        'joseph-kuwashima',
      ],
      relatedFamilyIds: [],
    },
    {
      id: 'life-young-professional',
      name: 'Life / Young Professional',
      description:
        'LIFe stands for Lynchburg International Fellowship. We meet weekly for worship, Bible study, and fellowship. Contact the group leader for address. Join our WhatsApp group to stay updated on our weekly meeting agenda.',
      leaderIds: ['lin-ho', 'tyler-levin', 'gillian-tang', 'kevin-tang'],
      memberIds: [
        'daini-eades',
        'asia-brady',
        'jacob-eades',
        'gillian-tang',
        'lin-ho',
        'jake-guerrero',
        'faith-lang',
        'tyler-levin',
        'steven-ni',
        'brandon-roos',
        'miranda-sparklin',
        'ryan-sparklin',
        'amber-wang',
        'kevin-tang',
        'charley-xia',
        'moana-xia',
        'samantha-klotzbach',
      ],
      relatedFamilyIds: [],
    },
    {
      id: 'forest-young-family',
      name: 'Forest Family',
      description: 'We meet weekly for Bible study. This group provides childcare for ages 5–12.',
      leaderIds: ['qing-liu'],
      memberIds: [
        'zachary-daily',
        'lizhi-daily',
        'huina-hu',
        'yixin-jin',
        'rachel-liu',
        'yingguang-liu',
        'qing-liu',
        'zhenying-wang',
        'yu-zhou',
        'aihua-yi',
        'lianjie-xue',
        'weilong-zhuo',
      ],
      relatedFamilyIds: [],
    },
    {
      id: 'cornerstone-seniors',
      name: 'Cornerstone / Seniors',
      leaderIds: ['jay-song'],
      memberIds: [
        'kwan-cheng',
        'keimei-chang',
        'gordon-goh',
        'anna-goh',
        'lui-kuong-lai',
        'xiaosang-huang',
        'jay-song',
        'juiying-yu',
        'may-zhan',
      ],
      relatedFamilyIds: [],
    },
    {
      id: 'forty-plus-seniors',
      name: '40+ / Seniors',
      leaderIds: ['john-thompson'],
      memberIds: [
        'harmon-blanding',
        'janette-blanding',
        'jack-kerns',
        'brenda-kerns',
        'jennifer-mariner',
        'mark-miller',
        'vicki-miller',
        'iona-nixon',
        'shawn-thompson',
        'john-thompson',
      ],
      relatedFamilyIds: [],
    },
    {
      id: 'seekers',
      name: 'Seekers',
      leaderIds: [],
      memberIds: ['eva-brooks', 'diane-francis', 'faye-gallier', 'sandra-west'],
      relatedFamilyIds: [],
    },
    {
      id: 'men',
      name: "Men's Group (Chinese)",
      description: 'Read books to know Christ more!',
      leaderIds: [],
      memberIds: ['james-forbes'],
      relatedFamilyIds: [],
    },
    {
      id: 'youth',
      name: 'Youth',
      leaderIds: ['lin-ho', 'tyler-levin', 'gillian-tang'],
      memberIds: ['debbie-liu', 'bekkah-shi', 'gabriel-daily', 'becky-liu'],
      relatedFamilyIds: [],
    },
    {
      id: 'young-family-group',
      name: 'Young Family Group',
      leaderIds: ['long-cheng'],
      memberIds: [
        'long-cheng',
        'fangyu-ai',
        'daini-eades',
        'jacob-eades',
        'anne-park-braswell',
        'daniel-braswell',
        'miranda-sparklin',
        'ryan-sparklin',
      ],
      relatedFamilyIds: ['cheng-household', 'eades-family', 'braswell-family', 'sparklin-family'],
    },
  ],

  notes: [
    // ── Long Cheng (shepherd-1) logs ───────────────────────────────────────
    {
      id: 'note-1',
      personId: 'xiang-you',
      type: 'check-in',
      visibility: 'private',
      content: `Caught up with Bob after Sunday service. He seems to be settling in well — started attending the students group regularly. Mentioned he's been feeling some pressure with grad school deadlines. Encouraged him to stay connected.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(3),
    },
    {
      id: 'note-2',
      personId: 'daini-eades',
      type: 'prayer-request',
      visibility: 'private',
      content: `Daini reached out over WeChat. She and Jacob are navigating a difficult season — Jacob is between jobs and they're feeling the financial strain. Asked for prayer for wisdom and provision. Will follow up in person next week.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(7),
    },
    {
      id: 'note-3',
      personId: 'fangyu-ai',
      type: 'check-in',
      visibility: 'private',
      content: `Brief check-in with Fangyu on WeChat. She's been adjusting well to the new city. Mentioned she misses her family back home but finds the young family group really welcoming. Encouraged her to keep coming.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(14),
    },
    {
      id: 'note-4',
      personId: 'ryan-sparklin',
      type: 'general',
      visibility: 'private',
      content: `Called Ryan to check in. He and Miranda just had their second child — everyone is healthy! They're a bit overwhelmed with the newborn and a toddler but in good spirits. Offered to organize a meal train through the group.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(6),
    },
    {
      id: 'note-5',
      personId: 'jacob-eades',
      type: 'prayer-request',
      visibility: 'public',
      content:
        'Jacob came to me after service and opened up about the job search. He has two promising interviews next week. Prayed together. He appreciated it. Will keep checking in.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(2),
    },
    {
      id: 'note-6',
      personId: 'anne-park-braswell',
      type: 'check-in',
      visibility: 'private',
      content: `Texted Anne to see how she's doing. She's been busy with work and the kids' schedules but appreciated the message. Said she and Daniel are planning to attend the Young Family Group retreat.`,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(10),
    },
    {
      id: 'note-7',
      personId: 'zach-sun',
      type: 'event',
      visibility: 'public',
      content:
        'Met Zach at the church picnic. First time seeing him since he started attending. He seemed quiet but engaged. Introduced him to a few others in the students group. Will make a point to connect more intentionally.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(21),
    },
    {
      id: 'note-8',
      familyId: 'eades-family',
      type: 'event',
      visibility: 'private',
      content:
        'Had the Eades family over for dinner with two other young families. Great time of fellowship. The kids played together. Jacob and Daini opened up more in this setting — feeling more like they belong.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(18),
    },

    {
      id: 'note-lc-1',
      personId: 'miranda-sparklin',
      type: 'check-in',
      visibility: 'private',
      content: 'Checked in with Miranda — she and Ryan are adjusting well after the new baby.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(5),
    },
    {
      id: 'note-lc-2',
      personId: 'yu-ren-liu',
      type: 'prayer-request',
      visibility: 'private',
      content: 'Yu-Ren asked for prayer about a health concern in the family.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(9),
    },
    {
      id: 'note-lc-3',
      personId: 'david-green',
      type: 'general',
      visibility: 'private',
      content:
        'Brief chat with David after students fellowship — he seems to be finding his footing.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(4),
    },
    {
      id: 'note-lc-4',
      personId: 'mattaniah-wilson',
      type: 'check-in',
      visibility: 'private',
      content: 'Texted Mattaniah — he is busy with finals but still attending.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(12),
    },
    {
      id: 'note-lc-5',
      personId: 'joseph-kuwashima',
      type: 'event',
      visibility: 'private',
      content:
        'Joseph joined us for the small group hangout. First time he has come to a social event.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(3),
    },
    {
      id: 'note-lc-6',
      personId: 'zixuan-chen',
      type: 'check-in',
      visibility: 'private',
      content: 'Reached out to Zixuan via WeChat — short reply, seems occupied with school.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(16),
    },
    {
      id: 'note-lc-7',
      personId: 'michelle-wang',
      type: 'prayer-request',
      visibility: 'private',
      content: 'Michelle shared a prayer request about her parents visiting from out of town.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(5),
    },
    {
      id: 'note-lc-8',
      personId: 'cole-richards',
      type: 'general',
      visibility: 'private',
      content:
        'Bumped into Cole at the library — quick conversation, mentioned he has been coming more consistently.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(8),
    },
    {
      id: 'note-lc-9',
      personId: 'daniel-braswell',
      type: 'check-in',
      visibility: 'private',
      content:
        'Daniel stopped to chat after service — he and Anne are looking forward to the retreat.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(2),
    },
    {
      id: 'note-lc-10',
      personId: 'angelina-chen',
      type: 'prayer-request',
      visibility: 'private',
      content:
        'Angelina mentioned feeling spiritually dry lately. Encouraged her and prayed together.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(20),
    },
    {
      id: 'note-lc-11',
      personId: 'ce-liu',
      type: 'check-in',
      visibility: 'private',
      content: 'Quick WeChat message to Ce — he replied positively, coming again this Sunday.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(6),
    },
    {
      id: 'note-lc-12',
      personId: 'peter-macranie',
      type: 'general',
      visibility: 'private',
      content:
        'Introduced myself to Peter properly — he is newer to the group and appreciated the outreach.',
      createdBy: 'shepherd-1',
      createdAt: daysAgo(11),
    },

    // ── Asia Brady (shepherd-2) logs ───────────────────────────────────────
    {
      id: 'note-9',
      personId: 'gillian-tang',
      type: 'check-in',
      visibility: 'private',
      content: `Had coffee with Gillian after Wednesday prayer meeting. She's doing really well — very involved in the worship team. Mentioned she's been thinking about deeper Bible study and is considering joining the discipleship track.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(2),
    },
    {
      id: 'note-10',
      personId: 'moana-xia',
      type: 'prayer-request',
      visibility: 'private',
      content: `Moana called, quite distressed. She's been struggling with loneliness since moving here from the Bay Area. Her parents are also going through some health issues back home. Prayed with her on the phone. Plan to introduce her to a few more women in the group.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(10),
    },
    {
      id: 'note-11',
      personId: 'lin-ho',
      type: 'prayer-request',
      visibility: 'private',
      content:
        'Lisa messaged asking for prayer for her marriage — she and Tyler have been going through a rough patch. She seemed hesitant to share details but wanted someone to know. Encouraged her to consider speaking with Pastor Qing together. Praying for them.',
      createdBy: 'shepherd-2',
      createdAt: daysAgo(5),
    },
    {
      id: 'note-12',
      personId: 'ella-zajonc',
      type: 'check-in',
      visibility: 'private',
      content: `Texted Ella to check in — she missed the last two Sundays. She replied that she'd been traveling for work. Seems fine, just busy. Will follow up if she misses again.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(8),
    },
    {
      id: 'note-13',
      personId: 'natalie-cummings',
      type: 'general',
      visibility: 'private',
      content: `Natalie mentioned she's interested in getting baptized. She said she's been a believer for years but never took the step formally. Pointed her toward the membership class and will loop in Pastor Qing.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(15),
    },
    {
      id: 'note-14',
      personId: 'jessica-wang',
      type: 'check-in',
      visibility: 'public',
      content: `Good conversation with Jessica at the women's event. She's recently started a new job and loves it. Also mentioned she's been reading through the New Testament on her own — encouraged her.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(30),
    },
    {
      id: 'note-15',
      personId: 'gillian-tang',
      type: 'check-in',
      visibility: 'private',
      content: `Checked in via text before the holidays. Gillian said she's heading home to see family — asked for prayer for some family tension she anticipates. Will follow up when she returns.`,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(35),
    },

    // ── Admin (Pastor Qing) logs ────────────────────────────────────────────
    {
      id: 'note-16',
      personId: 'long-cheng',
      type: 'general',
      visibility: 'private',
      content: `Met with Long over lunch to review how his group is doing. He's handling things well but mentioned feeling stretched with his own life responsibilities. Encouraged him, reminded him shepherding is about relationship, not performance.`,
      createdBy: 'admin',
      createdAt: daysAgo(1),
    },
    {
      id: 'note-17',
      personId: 'tyler-levin',
      type: 'prayer-request',
      visibility: 'private',
      content: `Tyler pulled me aside after service. He and Lisa have been having some tension at home. He mentioned feeling disconnected from the church community. Asked for prayer and for some pastoral guidance. We'll meet for coffee next week.`,
      createdBy: 'admin',
      createdAt: daysAgo(4),
    },
    {
      id: 'note-18',
      personId: 'mark-miller',
      type: 'check-in',
      visibility: 'private',
      content: `Called Mark. He and Vicki have been faithful attendees. He mentioned they'd love to see more seniors get connected. We discussed the idea of a 40+ social event in the spring.`,
      createdBy: 'admin',
      createdAt: daysAgo(9),
    },
    {
      id: 'note-19',
      personId: 'rachel-liu',
      type: 'check-in',
      visibility: 'private',
      content: `Checked in with Rachel on WeChat. She's been coming consistently since transferring from another church. Seems eager to serve but still finding her footing. Suggested she connect with the welcome team.`,
      createdBy: 'admin',
      createdAt: daysAgo(12),
    },
    {
      id: 'note-20',
      personId: 'eric-chen',
      type: 'event',
      visibility: 'public',
      content:
        'Eric shared his testimony at the membership class — very moving. He credited the student group for helping him through a difficult time in his faith. The whole class was encouraged.',
      createdBy: 'admin',
      createdAt: daysAgo(25),
    },
  ],

  todos: [
    // ── Long Cheng (shepherd-1) todos ──────────────────────────────────────
    {
      id: 'todo-1',
      personId: 'daini-eades',
      title: `Follow up with Daini about Jacob's job situation`,
      dueDate: daysAhead(1),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(7),
    },
    {
      id: 'todo-2',
      personId: 'xiang-you',
      title: 'Check in with Bob after grad school deadline',
      dueDate: daysAhead(3),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(3),
    },
    {
      id: 'todo-3',
      personId: 'ryan-sparklin',
      title: 'Organize meal train for Sparklin family (new baby)',
      dueDate: daysAhead(2),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(6),
    },
    {
      id: 'todo-4',
      personId: 'jacob-eades',
      title: 'Send Jacob encouragement before his job interviews',
      dueDate: daysAhead(0),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(2),
    },
    {
      id: 'todo-5',
      personId: 'fangyu-ai',
      title: 'Monthly check-in with Fangyu',
      dueDate: daysAhead(7),
      repeat: 'monthly',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(14),
    },
    {
      id: 'todo-6',
      personId: 'anne-park-braswell',
      title: 'Confirm Anne & Daniel are coming to the Young Family retreat',
      dueDate: daysAgo(0),
      repeat: 'none',
      completed: true,
      completedAt: daysAgo(1),
      createdBy: 'shepherd-1',
      createdAt: daysAgo(10),
    },
    {
      id: 'todo-7',
      personId: 'zach-sun',
      title: 'Grab coffee with Zach — get to know him better',
      dueDate: daysAhead(10),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-1',
      createdAt: daysAgo(21),
    },

    // ── Asia Brady (shepherd-2) todos ──────────────────────────────────────
    {
      id: 'todo-8',
      personId: 'moana-xia',
      title: 'Introduce Moana to 2–3 women in the Life / YP group',
      dueDate: daysAhead(4),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(10),
    },
    {
      id: 'todo-9',
      personId: 'lin-ho',
      title: 'Follow up with Lisa — check how things are at home',
      dueDate: daysAhead(2),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(5),
    },
    {
      id: 'todo-10',
      personId: 'natalie-cummings',
      title: 'Connect Natalie with Pastor Qing re: baptism interest',
      dueDate: daysAhead(5),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(15),
    },
    {
      id: 'todo-11',
      personId: 'gillian-tang',
      title: 'Welcome Gillian back from family visit',
      dueDate: daysAhead(0),
      repeat: 'none',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(35),
    },
    {
      id: 'todo-12',
      personId: 'ella-zajonc',
      title: 'Check if Ella is back from her work travel',
      dueDate: daysAgo(1),
      repeat: 'none',
      completed: true,
      completedAt: daysAgo(1),
      createdBy: 'shepherd-2',
      createdAt: daysAgo(8),
    },
    {
      id: 'todo-13',
      personId: 'leanne-hanson',
      title: `Leanne's birthday`,
      dueDate: daysAhead(6),
      repeat: 'yearly',
      completed: false,
      createdBy: 'shepherd-2',
      createdAt: daysAgo(60),
    },

    // ── Admin (Pastor Qing) todos ───────────────────────────────────────────
    {
      id: 'todo-14',
      personId: 'tyler-levin',
      title: 'Coffee with Tyler — pastoral follow-up',
      dueDate: daysAhead(5),
      repeat: 'none',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(4),
    },
    {
      id: 'todo-15',
      personId: 'long-cheng',
      title: 'Monthly shepherd check-in with Long',
      dueDate: daysAhead(14),
      repeat: 'monthly',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(1),
    },
    {
      id: 'todo-16',
      personId: 'rachel-liu',
      title: 'Follow up with Rachel about joining Welcome Team',
      dueDate: daysAhead(7),
      repeat: 'none',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(12),
    },
    {
      id: 'todo-17',
      personId: 'mark-miller',
      title: 'Plan spring social event for 40+ group with Mark',
      dueDate: daysAhead(21),
      repeat: 'none',
      completed: false,
      createdBy: 'admin',
      createdAt: daysAgo(9),
    },
    {
      id: 'todo-18',
      personId: 'eric-chen',
      title: `Check in with Eric — see how he's doing post-testimony`,
      dueDate: daysAgo(3),
      repeat: 'none',
      completed: true,
      completedAt: daysAgo(3),
      createdBy: 'admin',
      createdAt: daysAgo(25),
    },
  ],
  notices: [],
};
